variable "aws_region" {
  description = "AWS region for the Lambda and API Gateway resources."
  type        = string
  default     = "us-east-1"
}

variable "name_prefix" {
  description = "Prefix used for all service resources."
  type        = string
  default     = "lambda-api-kronk"
}

variable "lambda_memory_size" {
  description = "Lambda memory size in MB."
  type        = number
  default     = 4096
}

variable "lambda_timeout" {
  description = "Lambda timeout in seconds."
  type        = number
  default     = 900
}

variable "lambda_ephemeral_storage_mb" {
  description = "Ephemeral storage for Lambda in MB."
  type        = number
  default     = 2048
}

variable "log_retention_days" {
  description = "CloudWatch log retention in days."
  type        = number
  default     = 7
}

variable "lambda_image_tag" {
  description = "Docker tag used for the Lambda runtime image in ECR."
  type        = string
  default     = "latest"
}

variable "ecr_state_path" {
  description = "Path to the Terraform state file generated by the ECR layer."
  type        = string
  default     = "../ecr/terraform.tfstate"
}
